name: Dyqan-Online2
url: http://dyqan-online.github.io
baseurl: /Dyqan-Online2
description: Produkte Te Ndryshme 
avatar: 
disqus: 
google_analytics: 
categoryConfigByCategory:
  Blog:
    display-style: post
    menu-position: -1
    header-position: 0
    foot-position: -1
siteConfigBySite:
  Github:
    link: https://github.com/LeeL-Systems
    display-style: socialMedia
    position: 0
markdown: kramdown
highlighter: pygments
permalink: /:title/
version: v1.0.0
sass:
  sass_dir: _scss
  style: :expanded
gems:
  - jemoji
  - jekyll-sitemap
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md